# Generated by Django 3.2.5 on 2021-08-20 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogpost', '0002_blogmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='BlogModel',
            old_name='content',
            new_name='question'
        )
    ]
