# Generated by Django 3.2.5 on 2021-08-21 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogpost', '0004_blogmodel_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogmodel',
            name='answer',
        ),
    ]
