# Generated by Django 3.2.5 on 2021-08-21 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogpost', '0005_remove_blogmodel_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmodel',
            name='answer',
            field=models.TextField(null=True),
        ),
    ]
